language: node_js
node_js:
  - 6
cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - commitlint-travis
  - yarn test --coverage
  - yarn build
  - yarn predeploy
deploy:
  - provider: npm
    skip_cleanup: true
    email: yassine@doghri.fr
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local_dir: example/build
    on:
      branch: master

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT